{"uid":"7f8f8fe3241f8d96","name":"Login with both admin and user credentials (example #1)","fullName":"API Testing for Login.Login with both admin and user credentials (example #1)","historyId":"1a87645b7af2c197001161e2effda4b1","time":{"start":1736027120509,"stop":1736027121156,"duration":647},"description":"","descriptionHtml":"","status":"broken","statusMessage":"`cy.request()` failed trying to load:\n                \n                http://localhost:7081/\n                \n                We attempted to make an http request to this URL but the request failed without a response.\n                \n                We received this error at the network level:\n                \n                  > Error: connect ECONNREFUSED 127.0.0.1:7081\n                \n                -----------------------------------------------------------\n                \n                The request we sent was:\n                \n                Method: OPTIONS\n                URL: http://localhost:7081/\n                \n                -----------------------------------------------------------\n                \n                Common situations why this would fail:\n                  - you don't have internet access\n                  - you forgot to run / boot your web server\n                  - your web server isn't accessible\n                  - you have weird network configuration settings on your computer\n                \n                https://on.cypress.io/request","statusTrace":"CypressError: `cy.request()` failed trying to load:\n                \n                http://localhost:7081/\n                \n                We attempted to make an http request to this URL but the request failed without a response.\n                \n                We received this error at the network level:\n                \n                  > Error: connect ECONNREFUSED 127.0.0.1:7081\n                \n                -----------------------------------------------------------\n                \n                The request we sent was:\n                \n                Method: OPTIONS\n                URL: http://localhost:7081/\n                \n                -----------------------------------------------------------\n                \n                Common situations why this would fail:\n                  - you don't have internet access\n                  - you forgot to run / boot your web server\n                  - your web server isn't accessible\n                  - you have weird network configuration settings on your computer\n                \n                https://on.cypress.io/request\n                    at <unknown> (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:132904:70)\n                    at tryCatcher (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1830:23)\n                    at <unknown> (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:4226:37)\n                    at tryCatcher (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1830:23)\n                    at Promise._settlePromiseFromHandler (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1542:31)\n                    at Promise._settlePromise (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1599:18)\n                    at Promise._settlePromise0 (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1644:10)\n                    at Promise._settlePromises (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:1720:18)\n                    at _drainQueueStep (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:2430:12)\n                    at _drainQueue (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:2423:9)\n                    at Async._drainQueues (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:2439:5)\n                    at Async.drainQueues (https://opensource-demo.orangehrmlive.com/__cypress/runner/cypress_runner.js:2309:14)\n                From Your Spec Code:\n                    at Login.loginUser (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:19087:21)\n                    at sendLoginRequest (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:19247:33)\n                    at Context.eval (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:19261:11)\n                    at Registry.runStepDefininition (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:10419:48)\n                    at Object.fn (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:17018:43)\n                    at runStepWithLogGroup (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:16478:29)\n                    at Context.eval (https://opensource-demo.orangehrmlive.com/__cypress/tests?p=cypress/e2e/tests/api/post/login.feature:17014:62)\n                \n                From Node.js Internals:\n                  RequestError: Error: connect ECONNREFUSED 127.0.0.1:7081\n                      at new r (<embedded>:227:404489)\n                      at ee.callback (<embedded>:227:410490)\n                      at e.callback.s.callback [as _callback] (<embedded>:227:409936)\n                      at s._callback.s.callback.s.callback (<embedded>:290:100275)\n                      at ee.emit (node:events:514:28)\n                      at ee.onRequestError (<embedded>:290:109217)\n                      at ClientRequest.emit (node:events:526:35)\n                      at Socket.socketErrorListener (node:_http_client:501:9)\n                      at Socket.emit (node:events:514:28)\n                      at emitErrorNT (node:internal/streams/destroy:151:8)\n                      at emitErrorCloseNT (node:internal/streams/destroy:116:3)\n                      at process.processTicksAndRejections (node:internal/process/task_queues:82:21)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"suite","value":"API Testing for Login"},{"name":"testClass","value":"API Testing for Login"},{"name":"testMethod","value":"Login with both admin and user credentials (example #1)"},{"name":"package","value":"API Testing for Login"},{"name":"resultFormat","value":"allure1"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"7f8f8fe3241f8d96.json","parameterValues":[]}